---

- name: include OS-specific vars
  ansible.builtin.include_vars: >-
    {{ lookup('ansible.builtin.first_found', __locale_vars_files) }}

- name: check if localectl exists
  ansible.builtin.command: which localectl
  check_mode: no
  changed_when: no
  failed_when: no
  register: __locale_localectl_cmd

- name: check if /etc/sysconfig exists
  ansible.builtin.stat:
    path: /etc/sysconfig
  changed_when: no
  failed_when: no
  register: __locale_sysconfig_dir

- name: set locale configuration to systemd
  ansible.builtin.set_fact:
    __locale_configuration: systemd
  when: >
    __locale_localectl_cmd.rc == 0

- name: set locale configuration to sysconfig
  ansible.builtin.set_fact:
    locale_configuration: sysconfig
  when: >
    __locale_localectl_cmd.rc != 0 and
    __locale_sysconfig_dir.stat.exists and
    __locale_sysconfig_dir.stat.isdir

- name: include locale configuration tasks
  ansible.builtin.include_tasks: '{{ __locale_configuration }}.yml'

...
