---

- name: include OS-specific vars
  ansible.builtin.include_vars: >-
    {{ lookup('ansible.builtin.first_found', __locale_vars_files) }}

- name: 'set system language in {{ __locale_conf_path }}'
  ansible.builtin.template:
    src: locale.conf.j2
    dest: '{{ __locale_conf_path }}'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: configure virtual console keyboard in /etc/vconsole.conf
  ansible.builtin.template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: configure keyboard in /etc/default/keyboard
  ansible.builtin.template:
    src: keyboard.j2
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  become: yes
  when:
    - __locale_os == 'debian'

...
