---

- name: include OS-specific vars
  ansible.builtin.include_vars: >-
    {{ lookup('ansible.builtin.first_found', __locale_vars_files) }}

- name: install packages
  ansible.builtin.package:
    name: '{{ __locale_packages }}'
    update_cache: '{{ __locale_virtualized }}'
  become: yes
  when:
    - __locale_packages is defined

- name: system language preflight checks
  ansible.builtin.include_tasks: preflight-locale.yml
  when:
    - system_language is defined

- name: 'set system language in {{ __locale_conf_path }}'
  ansible.builtin.template:
    src: locale.conf.j2
    dest: '{{ __locale_conf_path }}'
    owner: root
    group: root
    mode: 0644
  become: yes
  when:
    - system_language is defined

- name: keymap preflight checks
  ansible.builtin.include_tasks: preflight-keymap.yml
  when:
    - system_keymap is defined
    - __locale_os != "debian" # localectl list-keymaps unsupported

- name: configure virtual console keyboard in /etc/vconsole.conf
  ansible.builtin.template:
    src: '{{ lookup("first_found", __locale_vconsole_templates) }}'
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: configure keyboard in /etc/default/keyboard
  ansible.builtin.template:
    src: keyboard.j2
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  become: yes
  when:
    - __locale_os == 'debian'

...
