---

- name: converge
  hosts: all

  pre_tasks:

    - name: show discovered python interpreter
      ansible.builtin.debug:
        var: ansible_facts.discovered_interpreter_python

    - name: show discovered package manager
      ansible.builtin.debug:
        var: ansible_facts.pkg_mgr

    - name: update package cache (Arch Linux)
      community.general.pacman:
        update_cache: yes
      when:
        - ansible_facts.os_family == 'Archlinux'
      become: yes
      changed_when: no
      register: __update_package_cache
      until: __update_package_cache is success
      retries: 10
      delay: 2

    - name: update package cache (other distros)
      ansible.builtin.package:
        update_cache: yes
      when:
        - ansible_facts.os_family != 'Archlinux'
      become: yes
      changed_when: no
      register: __update_package_cache
      until: __update_package_cache is success
      retries: 10
      delay: 2

  tasks:
    - name: include role idiv_biodiversity.locale
      ansible.builtin.include_role:
        name: idiv_biodiversity.locale

...
