---

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
  inventory:
    host_vars:
      rockylinux-8:
        system_language: 'en_GB.utf8'
    group_vars:
      all:
        system_locales:
          - name: en_GB.UTF-8
            charset: UTF-8
          - name: en_US.UTF-8
            charset: UTF-8
        system_language: 'en_GB.UTF-8'
        system_keymap: 'dvorak-programmer'
        system_font: 'latarcyrheb-sun16'

...
