---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: archlinux
    image: carlodepieri/docker-archlinux-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: yes
    privileged: yes

  - name: rockylinux-8
    image: ghcr.io/hspaans/molecule-containers:rockylinux-8
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - nosudo

  - name: rockylinux-9
    image: ghcr.io/hspaans/molecule-containers:rockylinux-9
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    pre_build_image: yes
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - nosudo

provisioner:
  name: ansible
  inventory:
    group_vars:
      nosudo:
        ansible_become_method: su
    host_vars:
      archlinux:
        ansible_user: ansible

verifier:
  name: ansible

...
