---

name: Review GitHub Actions

on:
  pull_request:
    paths:
      - .github/workflows/*.ya?ml
  push:
    paths:
      - .github/workflows/*.ya?ml

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: run actionlint
        uses: reviewdog/action-actionlint@d39025c0fb1cc41ac827852403ea94804b0e6907 # v1.71.0

...
