---

name: Review GitHub Actions

on:
  pull_request:
    paths:
      - .github/workflows/*.ya?ml
  push:
    paths:
      - .github/workflows/*.ya?ml

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: run actionlint
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0

...
